### ISSUE TITLE
Missing support for triple hamsa ("hamsa hamsa hamsa")

### ISSUE THREAD

**Issue by amitayh** [ofiratt/hamsajs#2]
Triple hamsa is proven to be more effective than a single hamsa, please add support

**Comment by GBT3101** [comment]
Hi amitayh, sorry for the late reply.

It's a common mistake to think that Triple Hamsa (TH) yield better results.
The truth is, in the best case it yields the same results, at worst might even harm the BE protection.

Therefore we will not support TH.
Thank you for suggesting.
